language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations
  - python manage.py migrate --run-syncdb
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source=register,donation,complaint,map manage.py test

after_script:
  - coveralls